# Generated by Django 6.0 on 2026-01-30 18:17

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.CharField(default=catalog.models.generate_short_uuid, editable=False, max_length=22, primary_key=True, serialize=False, verbose_name='Зовнішній ID'),
        ),
    ]
