# Generated by Django 6.0 on 2026-01-20 12:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='external_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=255, unique=True, verbose_name='Зовнішній ID'),
        ),
    ]
