# Generated by Django 6.0 on 2026-01-20 14:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_external_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='external_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Зовнішній ID'),
        ),
    ]
